name: Playwright Visual Test

on:
  push:
    branches: [ "dev" ]

permissions:
  id-token: write
  contents: read

jobs:
  visual-regression-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Config AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::891319630860:role/GitHubDeployRole
          aws-region: us-east-1

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Download golden screenshot from S3
        run: |
          mkdir -p tests/pageuptime.spec.js-snapshots
          aws s3 cp s3://assets.paragonhydraulics.com/other/playwright/contactuspage-chromium-linux.png tests/pageuptime.spec.js-snapshots/contactuspage-chromium-linux.png

      - name: Run Playwright tests
        run: npx playwright test